---
title: "RWorksheet_Almayo#4a(2)"
output:
  pdf_document: default
  html_document: default
date: "2024-10-28"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
#6
```{r}

Num <- readline(prompt="Select a number between 1 to 50:")

if(Num<=1 || Num>=50){
  print("The number selected is beyond the range of 1 to 50")
}else if(Num==20){
  print("TRUE")
}else{
  print(Num)
}
```

#7
```{r}
Input <- 150
if(Input<=50){
  cat("Bill must be 50 pesos")
}else if (Input <=100 && Input >= 50){
  cat("Bill must be 100 pesos")
}else if (Input <= 200 && Input >=100){
  cat("Bill must be 200 pesos")
}else if (Input <= 500 && Input >= 200){
  cat("Bill must be 500 pesos")
}else if (Input <= 1000 && Input >= 500){
  cat("Bill must be 1000 pesos")
}
```

#8
```{r}
students <- data.frame(
Name = c("Annie", "Thea", "Steve", "Hanna"),
Grade1 = c(85, 65, 75, 95),
Grade2 = c(65, 75, 55, 75),
Grade3 = c(85, 90, 80, 100),
Grade4 = c(100, 90, 85, 90))
```

#B
```{r}
Annie <- "Annie"
Thea <- "Thea"
Steve <- "Steve"
Hannah <- "Hannah"
choice <- readline(prompt="Select Student: ")
if(choice == Annie){
  x <-(85+65+85+100)/4
  paste("Annie's average grade this semester is" ,x)
}else if(choice == Thea){
  y <- (65+75+90+75)/4
  paste("Thea's average grade this semester is" ,y)
}else if(choice == Steve){
  a <- (85+55+80+85)/4
  paste("Steve's average grade this semester is" ,a)
}else if (choice == Hannah){
  b <- (100+75+100+90)/4
  paste("Hannah's average grade this semester is" ,b)
}else{
  print("Select Again")
}
```
#C
```{r}
avg_res<- rowSums(students[, 2:5]) / 4
for (i in 1:nrow(students)) {
  if (avg_res[i] < 80) {
    cat("The", i, "test was difficult.\n")
  }
}
```

#D
```{r}
for (i in 1:nrow(students)) {
  highest_score <- max(students[i, 2:5]) 
  if (highest_score > 90) {
    cat(students$Name[i], "’s highest grade this semester is", highest_score, "\n")
  }
}
```






